#.github/workflows/workflow1.yml
name: workflow1
on :
  push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps :
    - name : checkout
      uses : actions/checkout@v2.0.0
    - run : date
  job2:
    runs-on: windows-latest
    steps :
    - name : checkout
      uses : actions/checkout@v2.0.0
    - run : date
  job3:
    runs-on: macos-latest
    steps :
    - name : checkout
      uses : actions/checkout@v2.0.0
    - run : date
  job4:
    runs-on: ubuntu-latest
    needs : [job1,job2,job3]
    steps :
    - name : checkout
      uses : actions/checkout@v2.0.0
    - run : date
